### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by xiazeyu** [xiazeyu/hentaiTagger4calibre#4]
- [x] remove unused tags
- [x] Chinese translate
- [x] check if all infos are provided
- [x] file logic instead of batch logic
- [x] Series
